In [14]:
#numpy array allows you to perform mathematical operations on entire arrays without the need for explicit loops. and manipulate large datasets efficiently.
import numpy as np

array_id = np.array([1, 2, 3, 4, 5])
matrix = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
result_Add = array_id + 10
result_Multiply = array_id * 2

print(result_Add)
print(result_Multiply)
print("\n")
print(matrix)
print("\n")

arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
result = arr_a + arr_b
print(result)

#numpy functions for mathematical operations
sqrt = np.sqrt(arr_a)
sqrt1 =np.sqrt(matrix)
exp = np.exp(arr_b) #exp is e raised to the power of each element in the array
exp1 = np.exp(matrix)

mean = np.mean(arr_a)
mean1 = np.mean(matrix)

std_dev = np.std(arr_b)

arr_broadcast = np.array([1,2,4])

print("\n")
print(sqrt)
print(sqrt1)
print("\n")
print(exp)
print("\n exp above")
print(mean)
print(mean1)

[11 12 13 14 15]
[ 2  4  6  8 10]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[5 7 9]


[1.         1.41421356 1.73205081]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


[ 54.59815003 148.4131591  403.42879349]

 exp above
2.0
5.0


In [ ]:
import numpy as np
random_uniform = np.random.uniform(0,69,1)
random_normal = np.random.normal(0,1,1) #random.normal gives us random numbers from a normal (Gaussian) distribution with a specified mean and standard deviation.
print(random_uniform)
print(random_normal)

random_array = np.random.rand(4,3) #rand gives us random 3x3 array from a uniform distribution over [0, 1), why from 0 to 1 because rand generates numbers in the range [0.0, 1.0)
print(random_array)

[12.75511104]
[0.84244977]
[[0.97857804 0.89421416 0.53242549]
 [0.60202083 0.42397885 0.9123764 ]
 [0.20537299 0.60234565 0.06855292]
 [0.01378067 0.32910131 0.20791351]]
